{{- if .Values.runScope.local -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "prometheus-container-resource-exporter.name" . }}
    chart: {{ template "prometheus-container-resource-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus-container-resource-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus-container-resource-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus-container-resource-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}